{{- if and (.Values.dags.gitSync.enabled) (.Values.dags.gitSync.sshKnownHosts) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.fullname" . }}-known-hosts
  labels:
    app: {{ include "airflow.labels.app" . }}
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.airflow.secretAnnotations }}
  annotations:
    {{- toYaml .Values.airflow.secretAnnotations | nindent 4 }}
  {{- end }}
stringData:
  known_hosts: |-
    {{- .Values.dags.gitSync.sshKnownHosts | nindent 4 }}
{{- end }}
